import { COLORS } from "./../../styles/colors";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.cinzaFundo,
  },
  scrollContent: {
    padding: 20,
    alignItems: "center",
  },
  header: {
    width: "100%",
    marginBottom: 30,
    alignItems: "center",
  },
  eventName: {
    fontSize: 22,
    fontWeight: "bold",
    color: COLORS.textoPrincipal,
    textAlign: "center",
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 16,
    color: COLORS.textoSecundario,
    textAlign: "center",
  },
  card: {
    width: "100%",
    backgroundColor: COLORS.branco,
    borderRadius: 16,
    padding: 24,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 5,
  },
  qrPlaceholder: {
    width: 250,
    height: 250,
    backgroundColor: "#f9f9f9",
    borderRadius: 16,
    borderWidth: 2,
    borderColor: "#e0e0e0",
    borderStyle: "dashed",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 20,
  },
  wordContainer: {
    width: "100%",
    backgroundColor: "#fce8e8",
    paddingVertical: 15,
    borderRadius: 12,
    alignItems: "center",
    marginBottom: 20,
    borderWidth: 1,
    borderColor: COLORS.vermelhoPrincipal,
  },
  wordLabel: {
    fontSize: 12,
    color: COLORS.vermelhoPrincipal,
    textTransform: "uppercase",
    fontWeight: "bold",
    marginBottom: 5,
  },
  wordText: {
    fontSize: 32,
    fontWeight: "700",
    letterSpacing: 4,
    color: COLORS.textoPrincipal,
  },
  timerContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 30,
  },
  timerText: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#e67e22",
    marginBottom: 8,
  },
  button: {
    width: "100%",
    backgroundColor: COLORS.vermelhoPrincipal,
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "center",
  },
  buttonText: {
    color: COLORS.branco,
    fontSize: 16,
    fontWeight: "bold",
    marginLeft: 8,
  },
  input: {
    width: "100%",
    borderWidth: 1,
    borderColor: "#d1d1d1",
    borderRadius: 8,
    padding: 15,
    fontSize: 16,
    textAlign: "center",
    marginBottom: 20,
    textTransform: "uppercase",
  },
  helperText: {
    fontSize: 14,
    color: COLORS.textoSecundario,
    textAlign: "center",
    marginBottom: 20,
    lineHeight: 20,
  },
});
