import { StyleSheet } from "react-native";
import { COLORS } from "../../styles/colors";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.cinzaFundo,
  },
  scrollContent: {
    padding: 20,
    paddingBottom: 40,
  },
  imageUploadArea: {
    backgroundColor: COLORS.branco,
    height: 180,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#E0E0E0',
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 5,
    elevation: 2,
  },
  imageUploadText: {
    color: COLORS.textoSecundario,
    marginTop: 10,
    fontSize: 14,
  },
  formSection: {
    backgroundColor: COLORS.branco,
    padding: 20,
    borderRadius: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 3,
    marginBottom: 20,
  },
  inputGroup: {
    marginBottom: 20, 
  },
  label: {
    fontSize: 14,
    fontWeight: "bold",
    color: COLORS.textoPrincipal,
    marginBottom: 8,
  },
  input: {
    backgroundColor: COLORS.branco,
    borderWidth: 1.5, 
    borderColor: COLORS.vermelhoPrincipal,
    borderRadius: 10, 
    paddingHorizontal: 15,
    paddingVertical: 14, 
    fontSize: 16,
    color: COLORS.textoPrincipal,
  },
  inputDisabled: {
    backgroundColor: "#F5F5F5",
    borderColor: "#E0E0E0",
    color: "#A0A0A0",
  },
  textArea: {
    height: 120,
    textAlignVertical: "top",
  },
  switchGroup: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#F9F9F9",
    padding: 15,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#E0E0E0",
    marginBottom: 20,
  },
  switchLabel: {
    fontSize: 16,
    fontWeight: "600",
    color: COLORS.textoPrincipal,
  },
  submitButton: {
    backgroundColor: COLORS.vermelhoPrincipal,
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: "center",
    shadowColor: COLORS.vermelhoPrincipal,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  submitButtonText: {
    color: COLORS.branco,
    fontSize: 18,
    fontWeight: "bold",
  },
});